export { default as Login } from './login';
export { default as Home } from './Home';
export { default as Newsletter } from './Newsletter';
export { default as Todos } from './Todos';
export { default as ToDo } from './ToDo';
export { default as Test } from './Test';
export { default as Register } from './Register';
export { default as User } from './User';
export { default as Users} from './Users';
export { default as Coctail} from './Coctail';
export { default as Stat} from './Stat';
export { default as Calendar} from './RESERVATION/Calendar';